apiVersion: v1
kind: Namespace
metadata:
  name: hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hello-world
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
  namespace: hello-world
spec:
  to:
    kind: Service
    name: nginx-service
  port:
    targetPort: 80